# Generated by Django 4.2.3 on 2023-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(),
        ),
    ]
