# Generated by Django 4.2.3 on 2023-07-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.TextField(null='no-username'),
            preserve_default='no-username',
        ),
    ]
