# Generated by Django 4.2.3 on 2023-07-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=30, null='no-username'),
        ),
    ]
